<?php
require_once 'db.php';
include 'header.php';
?>

<div class="container">
    <div class="pro-card" style="max-width: 850px; margin: 40px auto; padding: 40px; display: block; opacity: 1; transform: none;">
        <h1 style="color: white; margin-bottom: 25px;">Terms & Conditions</h1>
        <div style="color: var(--text-secondary); line-height: 1.8;">
            <p>Welcome to PromptKing. By accessing this website, you agree to be bound by these terms and conditions.</p>
            
            <h3 style="color: white; margin: 25px 0 10px;">1. Intellectual Property</h3>
            <p>Unless otherwise stated, PromptKing owns the intellectual property rights for all material on the website. You may access this for personal use, but you must not republish or sell our prompts without permission.</p>

            <h3 style="color: white; margin: 25px 0 10px;">2. User Content</h3>
            <p>Parts of this website offer an opportunity for users to post and exchange opinions. PromptKing does not filter or edit comments prior to their presence on the website.</p>

            <h3 style="color: white; margin: 25px 0 10px;">3. Disclaimer of Liability</h3>
            <p>We do not guarantee the results generated by external AI models using our prompts. Use of AI tools is at your own discretion and risk.</p>
        </div>
    </div>
</div>

<?php include 'footer.php'; ?>
