import ClientDisclaimerPage from './ClientDisclaimerPage';

export default function DisclaimerPage() {
  return (
    <>
      <div
        aria-hidden="false"
        style={{
          position: 'absolute', width: '1px', height: '1px', padding: 0,
          margin: '-1px', overflow: 'hidden', clip: 'rect(0,0,0,0)',
          whiteSpace: 'nowrap', border: 0,
        }}
      >
        <h1>Disclaimer - PromptKing</h1>
        <p>
          This disclaimer governs your use of the PromptKing website and all content, services,
          and AI prompts available on the platform. The information and prompts provided on
          PromptKing are for general informational and creative purposes only. While we strive to
          ensure that all prompts produce high-quality results, PromptKing makes no warranties or
          representations regarding the accuracy, completeness, or suitability of any AI-generated
          content. The results generated by AI tools using our prompts may vary depending on the
          specific AI model, version, and settings used. PromptKing is not responsible for any
          decisions made based on AI-generated content. Users are responsible for verifying the
          accuracy and appropriateness of any AI output before using it in professional or commercial
          contexts. Our platform contains links to third-party websites and AI tools for which we
          are not responsible. Use of any AI prompts from PromptKing is at your own discretion and risk.
        </p>
      </div>
      <ClientDisclaimerPage />
    </>
  );
}
